import { NgModule } from '@angular/core';
import { ConfirmDialogModule } from 'primeng/primeng';

import {
  MenuModule,
  FileUploadModule,
  ProgressSpinnerModule,
  AutoCompleteModule,
  PanelModule,
  ChartModule,
  InputTextModule,
  ButtonModule,
  InputMaskModule,
  InputTextareaModule,
  EditorModule,
  CalendarModule,
  RadioButtonModule,
  FieldsetModule,
  DropdownModule,
  MultiSelectModule,
  ListboxModule,
  SpinnerModule,
  SliderModule,
  RatingModule,
  DataTableModule,
  ContextMenuModule,
  TabViewModule,
  DialogModule,
  StepsModule,
  ScheduleModule,
  TreeModule,
  GMapModule,
  DataGridModule,
  TooltipModule,
  GrowlModule,
  DragDropModule,
  GalleriaModule,
  CheckboxModule
} from 'primeng/primeng';
import { TableModule } from 'primeng/table';

@NgModule({
  imports: [
    MenuModule,
    FileUploadModule,
    ProgressSpinnerModule,
    ConfirmDialogModule,
    PanelModule,
    TableModule,
    ChartModule,
    InputTextModule,
    ButtonModule,
    InputMaskModule,
    InputTextareaModule,
    EditorModule,
    CalendarModule,
    RadioButtonModule,
    AutoCompleteModule,
    FieldsetModule,
    DropdownModule,
    MultiSelectModule,
    ListboxModule,
    SpinnerModule,
    SliderModule,
    RatingModule,
    DataTableModule,
    ContextMenuModule,
    TabViewModule,
    DialogModule,
    StepsModule,
    ScheduleModule,
    TreeModule,
    GMapModule,
    DataGridModule,
    TooltipModule,
    ConfirmDialogModule,
    GrowlModule,
    DragDropModule,
    GalleriaModule,
    CheckboxModule,
    InputMaskModule
  ],
  exports: [
    MenuModule,
    InputMaskModule,
    CheckboxModule,
    ConfirmDialogModule,
    AutoCompleteModule,
    PanelModule,
    ChartModule,
    InputTextModule,
    ButtonModule,
    InputMaskModule,
    InputTextareaModule,
    EditorModule,
    CalendarModule,
    RadioButtonModule,
    FieldsetModule,
    DropdownModule,
    MultiSelectModule,
    ProgressSpinnerModule,
    ListboxModule,
    TableModule,
    FileUploadModule,
    SpinnerModule,
    SliderModule,
    RatingModule,
    DataTableModule,
    ContextMenuModule,
    TabViewModule,
    DialogModule,
    StepsModule,
    ScheduleModule,
    TreeModule,
    GMapModule,
    DataGridModule,
    TooltipModule,
    ConfirmDialogModule,
    GrowlModule,
    DragDropModule,
    GalleriaModule
  ],
  declarations: [],
  providers: []
})
export class PrimeNGModule {}
